// token
export const SET_TOKEN = 'SET_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

// appInfo
export const CHECK_WEIXIN = 'CHECK_WEIXIN';
export const INIT_APP_INFO = 'INIT_APP_INFO';
export const GET_WEIXIN_CONFIG_REQUEST = '';
export const GET_WEIXIN_CONFIG_SUCCESS = '';
export const GET_WEIXIN_CONFIG_FAILURE = '';

// toast
export const TOAST_SHOW = 'TOAST_SHOW';
export const TOAST_HIDE = 'TOAST_HIDE';

// loading
export const LOADING_SHOW = 'LOADING_SHOW';
export const LOADING_HIDE = 'LOADING_HIDE';

// alert
export const ALERT_SHOW = 'ALERT_SHOW';
export const ALERT_HIDE = 'ALERT_HIDE';

export const GET_CAR_BRAND = 'GET_CAR_BRAND';
export const GET_CAR_LINE  = 'GET_CAR_LINE';
export const GET_CAR_MODEL = 'GET_CAR_MODEL';
export const GET_CAR_BASE_INFO = '';
export const SET_CHOSEN_INFO = 'SET_CHOSEN_INFO';
export const SET_TMP_CHOSEN_INFO = 'SET_TMP_CHOSEN_INFO';
export const GET_BASE_INFO_BEFORE = 'GET_BASE_INFO_BEFORE';
export const GET_BASE_INFO_UPDATE = 'GET_BASE_INFO_UPDATE';
export const GET_BASE_INFO_RESET  = 'GET_BASE_INFO_RESET';

// home
export const GET_HOME_MENU_INIT    = 'GET_HOME_MENU_INIT';
export const GET_HOME_MENU_REQUEST = 'GET_HOME_MENU_REQUEST';
export const GET_HOME_MENU_SUCCESS = 'GET_HOME_MENU_SUCCESS';
export const GET_HOME_MENU_FAILURE = 'GET_HOME_MENU_FAILURE';
export const GET_ARTICLE_CATES_REQUEST = 'GET_ARTICLE_CATES_REQUEST';
export const GET_ARTICLE_CATES_SUCCESS = 'GET_ARTICLE_CATES_SUCCESS';
export const GET_ARTICLE_CATES_FAILURE = 'GET_ARTICLE_CATES_FAILURE';
export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE';
export const GET_DROP_MENU_REQUEST    = 'GET_DROP_MENU_REQUEST';
export const GET_DROP_MENU_SUCCESS    = 'GET_DROP_MENU_SUCCESS';
export const GET_DROP_MENU_FAILURE    = 'GET_DROP_MENU_FAILURE';

// articleDetail
export const GET_ARTICLE_DETAIL_REQUEST = 'GET_ARTICLE_DETAIL_REQUEST';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAILURE = 'GET_ARTICLE_DETAIL_FAILURE';
export const ARTICLE_DETAIL_RESET       = 'ARTICLE_DETAIL_RESET';
// articleList (search)
export const GET_SEARCH_ARTLIST_REQUEST = 'GET_SEARCH_ARTLIST_REQUEST';
export const GET_SEARCH_ARTLIST_SUCCESS = 'GET_SEARCH_ARTLIST_SUCCESS';
export const GET_SEARCH_ARTLIST_FAILURE = 'GET_SEARCH_ARTLIST_FAILURE';
export const TOOGLE_SEARCH_LIST_TYPE    = 'TOOGLE_SEARCH_LIST_TYPE';
export const SEARCH_INPUT_CHANGE        = 'SEARCH_INPUT_CHANGE';
export const SEARCH_TEM_INPUT_CHANGE    = 'SEARCH_TEM_INPUT_CHANGE';
export const GET_SEARCH_ARTLIST_RESET   = 'GET_SEARCH_ARTLIST_RESET';
export const GET_SEARCH_ARTLIST_CATES_REQUEST = 'GET_SEARCH_ARTLIST_CATES_REQUEST';
export const GET_SEARCH_ARTLIST_CATES_SUCCESS = 'GET_SEARCH_ARTLIST_CATES_SUCCESS';
export const GET_SEARCH_ARTLIST_CATES_FAILURE = 'GET_SEARCH_ARTLIST_CATES_FAILURE';

// maintenance
export const GET_MAINTENANCE_DETAIL_REQUEST = 'GET_MAINTENANCE_DETAIL_REQUEST';
export const GET_MAINTENANCE_DETAIL_SUCCESS = 'GET_MAINTENANCE_DETAIL_SUCCESS';
export const GET_MAINTENANCE_DETAIL_FAILURE = 'GET_MAINTENANCE_DETAIL_FAILURE';
export const GET_MAINTENANCE_DETAIL_RESET   = 'GET_MAINTENANCE_DETAIL_RESET';

// carModelDetail
export const GET_CAR_MODEL_DETAIL_REQUEST = 'GET_CAR_MODEL_DETAIL_REQUEST';
export const GET_CAR_MODEL_DETAIL_SUCCESS = 'GET_CAR_MODEL_DETAIL_SUCCESS';
export const GET_CAR_MODEL_DETAIL_FAILURE = 'GET_CAR_MODEL_DETAIL_FAILURE';
export const GET_CAR_MODEL_DETAIL_RESET   = 'GET_CAR_MODEL_DETAIL_RESET';
// carPart
export const GET_CAR_PART_NAME_REQUEST = 'GET_CAR_PART_NAME_REQUEST';
export const GET_CAR_PART_NAME_SUCCESS = 'GET_CAR_PART_NAME_SUCCESS';
export const GET_CAR_PART_NAME_FAILURE = 'GET_CAR_PART_NAME_FAILURE';
export const GET_CAR_PART_CATES_REQUEST = 'GET_CAR_PART_CATES_REQUEST';
export const GET_CAR_PART_CATES_SUCCESS = 'GET_CAR_PART_CATES_SUCCESS';
export const GET_CAR_PART_CATES_FAILURE = 'GET_CAR_PART_CATES_FAILURE';
export const CAR_PART_RESET             = 'CAR_PART_RESET';

// carPartDetail
export const GET_CAT_PART_DETAIL_BASE_REQUEST  = 'GET_CAT_PART_DETAIL_BASE_REQUEST';
export const GET_CAT_PART_DETAIL_BASE_SUCCESS  = 'GET_CAT_PART_DETAIL_BASE_SUCCESS';
export const GET_CAT_PART_DETAIL_BASE_FAILURE  = 'GET_CAT_PART_DETAIL_BASE_FAILURE';
export const GET_CAT_PART_DETAIL_PRICE_REQUEST = 'GET_CAT_PART_DETAIL_PRICE_REQUEST';
export const GET_CAT_PART_DETAIL_PRICE_SUCCESS = 'GET_CAT_PART_DETAIL_PRICE_SUCCESS';
export const GET_CAT_PART_DETAIL_PRICE_FAILURE = 'GET_CAT_PART_DETAIL_PRICE_FAILURE';
export const GET_CAT_PART_DETAIL_BRAND_REQUEST = 'GET_CAT_PART_DETAIL_BRAND_REQUEST';
export const GET_CAT_PART_DETAIL_BRAND_SUCCESS = 'GET_CAT_PART_DETAIL_BRAND_SUCCESS';
export const GET_CAT_PART_DETAIL_BRAND_FAILURE = 'GET_CAT_PART_DETAIL_BRAND_FAILURE';
export const GET_CAT_PART_DETAIL_IMG_REQUEST   = 'GET_CAT_PART_DETAIL_IMG_REQUEST';
export const GET_CAT_PART_DETAIL_IMG_SUCCESS   = 'GET_CAT_PART_DETAIL_IMG_SUCCESS';
export const GET_CAT_PART_DETAIL_IMG_FAILURE   = 'GET_CAT_PART_DETAIL_IMG_FAILURE';
export const CAR_PART_DETAIL_RESET = 'CAR_PART_DETAIL_RESET';

// 汽修资料列表 - 通用分类
export const GET_COMMON_LIB_LIST_REQUEST = 'GET_COMMON_LIB_LIST_REQUEST';
export const GET_COMMON_LIB_LIST_SUCCESS = 'GET_COMMON_LIB_LIST_SUCCESS';
export const GET_COMMON_LIB_LIST_FAILURE = 'GET_COMMON_LIB_LIST_FAILURE';
export const GET_COMMON_LIB_LIST_RESET   = 'GET_COMMON_LIB_LIST_RESET';

// 汽修资料列表 - 专业分类
export const GET_MAJOR_LIB_LIST_REQUEST = 'GET_MAJOR_LIB_LIST_REQUEST';
export const GET_MAJOR_LIB_LIST_SUCCESS = 'GET_MAJOR_LIB_LIST_SUCCESS';
export const GET_MAJOR_LIB_LIST_FAILURE = 'GET_MAJOR_LIB_LIST_FAILURE';
export const GET_MAJOR_LIB_LIST_RESET   = 'GET_MAJOR_LIB_LIST_RESET';

// 汽修资料详情
export const GET_LIB_DETAIL_REQUEST = 'GET_LIB_DETAIL_REQUEST';
export const GET_LIB_DETAIL_SUCCESS = 'GET_LIB_DETAIL_SUCCESS';
export const GET_LIB_DETAIL_FAILURE = 'GET_LIB_DETAIL_FAILURE';
export const GET_LIB_DETAIL_RESET   = 'GET_LIB_DETAIL_RESET';

// modelSearch
export const GET_MODEL_SEARCH_REQUEST = 'GET_MODEL_SEARCH_REQUEST';
export const GET_MODEL_SEARCH_SUCCESS = 'GET_MODEL_SEARCH_SUCCESS';
export const GET_MODEL_SEARCH_FAILUER = 'GET_MODEL_SEARCH_FAILUER';
export const GET_MODEL_SEARCH_RESET = 'GET_MODEL_SEARCH_RESET';

// 车辆配件分级结 & 单级配件
export const GET_CAR_STRUCT_REQUEST = 'GET_CAR_STRUCT_REQUEST';
export const GET_CAR_STRUCT_SUCCESS = 'GET_CAR_STRUCT_SUCCESS';
export const GET_CAR_STRUCT_FAILURE = 'GET_CAR_STRUCT_FAILURE';
export const GET_SINGLE_STRUCT_REQUEST = 'GET_SINGLE_STRUCT_REQUEST';
export const GET_SINGLE_STRUCT_SUCCESS = 'GET_SINGLE_STRUCT_SUCCESS';
export const GET_SINGLE_STRUCT_FAILURE = 'GET_SINGLE_STRUCT_FAILURE';

// modelInfo
export const GET_MODEL_INFO_REQUEST = 'GET_MODEL_INFO_REQUEST';
export const GET_MODEL_INFO_SUCCESS = 'GET_MODEL_INFO_SUCCESS';
export const GET_MODEL_INFO_FAILURE = 'GET_MODEL_INFO_FAILURE';
export const GET_MODEL_INFO_RESET = 'GET_MODEL_INFO_RESET';

// 优化下级分类
export const GET_LIB_GRADE_MENU_REQUEST = 'GET_LIB_GRADE_MENU_REQUEST';
export const GET_LIB_GRADE_MENU_SUCCESS = 'GET_LIB_GRADE_MENU_SUCCESS';
export const GET_LIB_GRADE_MENU_FAILURE = 'GET_LIB_GRADE_MENU_FAILURE';
export const GET_LIB_GRADE_MENU_RESET = 'GET_LIB_GRADE_MENU_RESET';
